* COMMENT -*- Mode: org; -*-

#+TITLE: ConwayGOL.sh

* About

Conway's Game of Life implementation on shell script.

* Usage

Those scripts in below of this section are tested on
MacOS 10.9 and CentOS 7.2.

Initialize environment.

#+BEGIN_SRC 
. rc
#+END_SRC

Initial pattern.

#+BEGIN_SRC 
initpattern example-pattern/glider
#+END_SRC

One step execution.

#+BEGIN_SRC 
initpattern example-pattern/glider	|
conwaygol
#+END_SRC

2 step execution.

#+BEGIN_SRC 
initpattern example-pattern/glider	|
conwaygol				| 
conwaygol
#+END_SRC

Play infinite steps on your entire terminal.
This will stop with no change between each step.
Press Ctrl-C to abort execution.

#+BEGIN_SRC 
playgol bin/conwaygol example-pattern/glider
#+END_SRC

You can record the cell changes...

#+BEGIN_SRC 
playgol bin/conwaygol example-pattern/glider	|
tee rec
#+END_SRC

and also can replay it.

#+BEGIN_SRC 
cat rec			|
while read l ; do
	echo "$l"
	sleep 1
done
#+END_SRC

* File tree

+ ConwayGoL
  + .git            : git system directory
  - .gitignore      : git ignoring file definition
  - README.org      : This README file
  - LICENSE         : About License
  - rc              : Set Environment paramters while development

  + bin             : Scripts directory
    - conwaygol     : Conway's game of life implementation

  + util            : Utility directory
    - initpattern   : Allocate pattern onto specified canvas
    - playgol       : Play game of life script

  + example-pattern : Example patterns directory
    - README.org    : README file of the directory

    - ... some pattern files ...

* References

https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B2%E3%83%BC%E3%83%A0

http://math.shinshu-u.ac.jp/~hanaki/lifegame/
