#!/bin/sh

LANG=C

pname="$(basename "$0")"
stime="$(date +%Y%m%d%H%M%S)"
tmp="/tmp/$pname.$stime.$$"

trap 'rm -f $tmp-*' EXIT

######################################################################

pattern=${1:-"-"}

X=${2:-"10"}
Y=${3:-"10"}

dX=${4:-"0"}
dY=${5:-"0"}

######################################################################

mkfifo "$tmp-base"

tr '\0' '_'	< /dev/zero	|
    fold -w "$X"		|
    head -n "$Y"	> "$tmp-base"	&

## == narrow $X $Y 0 0
awk -v FS='' -v X="$X" -v Y="$Y" -v dX="$dX" -v dY="$dY"	'
	NR > Y	{
		print "'"$pname.$stime.$$ INFO cell row overflow, choped."'"	> "/dev/stderr";
		exit 0;
	}
	(length() > X)	{
		print "'"$pname.$stime.$$ INFO cell colmun overflow, choped."'"	> "/dev/stderr";
	}
	{	print substr($0,1,'"$X"')	}'	"$pattern"	|
    # == ido 1 1
    awk -v FS='' -v X="$X" -v Y="$Y" -v dX="$dX" -v dY="$dY"	'
    	BEGIN{	for(i=0;i<dY;i++) print
		h=""
		for(i=0;i<dX;i++) h = h " "	}
	{	print h $0 }'						|
    # translate
    tr ' ' '_'		|
    tr -c '_\n' 'X'	|
    # == overlay "$tmp-base" -
    paste -d'\0' "$tmp-base" -						|
    awk -v FS='' -v X="$X" -v Y="$Y" -v dX="$dX" -v dY="$dY"	'
	((l = length()) == X)	{
		print ; next ;	}
	{	print substr($0,X+1,l-X) substr($0,l-X+1,2 * X-l)	}'|
    #
    cat
