#!/bin/sh

LANG=C

pname="$(basename "$0")"
stime="$(date +%Y%m%d%H%M%S)"
tmp="/tmp/$pname.$stime.$$"

trap 'rm -f $tmp-*' EXIT

######################################################################

golscript=${1}
pattern=${2:-"-"}
X=${3:-"$(($(tput cols) - 0))"}
Y=${4:-"$(($(tput lines) - 0))"}
n=${5}

######################################################################

# printf "\033[1;1H\033[2JX"
# printf "\033[%d;%dHX" $((Y - 0)) $((X - 0))
# read

# exit 0

mkfifo "$tmp-f0.fifo" "$tmp-f1.fifo"

refresh()	{
    frame0=${1}

    tr '_' ' '	< "$frame0"	|
	awk -v FS=""	'
	{	for(i=1;i<=NF;i++)
			printf("\033[%s;%sH%s\n", NR, i, $(i))
	}'	> "$tmp-f0.fifo"	&

    tr '_' ' '			|
	awk -v FS=""	'
	{	for(i=1;i<=NF;i++)
			printf("\033[%s;%sH%s\n", NR, i, $(i))
	}'	> "$tmp-f1.fifo"	&

    diff "$tmp-f0.fifo" "$tmp-f1.fifo"	|
	grep '^>'			|
	sed -e 's/^> //'		|
	tr -d '\n'
}

initpattern "$pattern" "$X" "$Y" 0 0	|
    tee "$tmp-current"			|
    tr '_' ' '				|
    awk '{	printf("\033[%d;1H%s", NR, $0)	}'

yes			|
    if [ "$n" ] ; then
	head -n "$n"
    else
	cat
    fi			|
while read ; do
    printf "\033[1;1H\n"
    "$golscript" "$tmp-current" "$X" "$Y"	|
	tee "$tmp-mid"				|
	refresh "$tmp-current"			|
	tee "$tmp-out"

    mv "$tmp-mid" "$tmp-current"

    if [ ! -s "$tmp-out" ] ; then
	break
    fi
done

printf "\033[1;1H"

exit 0
