#!/bin/sh

LANG=C

pname="$(basename "$0")"
stime="$(date +%Y%m%d%H%M%S)"
tmp="/tmp/$pname.$stime.$$"

trap 'rm -f $tmp-*' EXIT

######################################################################

golscript=${1}
pattern=${2:-"-"}
step=${3}
sleep=${4:-"0"}
X=${5:-"$(tput cols)"}
Y=${6:-"$(tput lines)"}

######################################################################

printf "\033[1;1H\n\033[2J\n"
initpattern "$pattern" "$X" "$Y" 0 0	|
    tee "$tmp-current"			|
    awk -v FS=""	'
	{	for(i=1;i<=NF;i++)
			printf("\033[%s;%sH%s\n", NR, i, $(i))
	}'	> "$tmp-current.x"

awk '{	printf("\033[%d;1H%s", NR, $0)	}' "$tmp-current"

yes			|
    if [ "$step" ] ; then
	head -n "$step"
    else
	cat
    fi			|
while read ; do
    printf "\033[1;1H\n"
    sleep "$sleep"

    "$golscript" "$tmp-current" "$X" "$Y"	|
	tee "$tmp-next"				|
	awk -v FS=""	'
	{	for(i=1;i<=NF;i++)
			printf("\033[%s;%sH%s\n", NR, i, $(i))
	}'					|
	tee "$tmp-next.x"			|
	diff "$tmp-current.x" -			|
	grep '^>'				|
	sed -e 's/^> //'			|
	tr -d '\n'				|
	tee "$tmp-out"

    [ -s "$tmp-out" ]	||	break

    mv "$tmp-next" "$tmp-current"
    mv "$tmp-next.x" "$tmp-current.x"
done

printf "\033[${Y};${X}H\n"

exit 0
