#!/bin/sh

LANG=C

pname="$(basename "$0")"
stime="$(date +%Y%m%d%H%M%S)"
tmp="/tmp/$pname.$stime.$$"

trap 'rm -f $tmp-*' EXIT

######################################################################

X="$1"
Y="$2"

txt="${3:-"-"}"

pad="$4"

[ "$#" -lt 4 ]	&& pad=" "

######################################################################

cat "$txt"		|
# trancelator
    if [ -z "$pad" ] ; then
	awk -v X="$X" -v Y="$Y" -v pad="$pad"	'
	{	len = length()
		for(i = 1; i<= len; i++)
			printf("2 %d %d %d %d %s\n", X, Y, i, NR, substr($0, i, 1))
	}'
    else
	awk -v X="$X" -v Y="$Y" -v pad="$pad"	'
	{	len = length()
		for(i = 1; i<= len; i++)	if(substr($0, i, 1) != pad)
			printf("2 %d %d %d %d %s\n", X, Y, i, NR, substr($0, i, 1))
	}'
    fi
    
######################################################################
exit 0
